In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv('gym_members_exercise_tracking.csv')
df.head(10)

Age  Gender  Weight (kg)  Height (m)  Max_BPM  Avg_BPM  Resting_BPM  \
0   56    Male         88.3        1.71      180      157           60   
1   46  Female         74.9        1.53      179      151           66   
2   32  Female         68.1        1.66      167      122           54   
3   25    Male         53.2        1.70      190      164           56   
4   38    Male         46.1        1.79      188      158           68   
5   56  Female         58.0        1.68      168      156           74   
6   36    Male         70.3        1.72      174      169           73   
7   40  Female         69.7        1.51      189      141           64   
8   28    Male        121.7        1.94      185      127           52   
9   28    Male        101.8        1.84      169      136           64   

   Session_Duration (hours)  Calories_Burned Workout_Type  Fat_Percentage  \
0                      1.69           1313.0         Yoga            12.6   
1                      1.30            883.0         HIIT            33.9   
2                      1.11            677.0       Cardio            33.4   
3                      0.59            532.0     Strength            28.8   
4                      0.64            556.0     Strength            29.2   
5                      1.59           1116.0         HIIT            15.5   
6                      1.49           1385.0       Cardio            21.3   
7                      1.27            895.0       Cardio            30.6   
8                      1.03            719.0     Strength            28.9   
9                      1.08            808.0       Cardio            29.7   

   Water_Intake (liters)  Workout_Frequency (days/week)  Experience_Level  \
0                    3.5                              4                 3   
1                    2.1                              4                 2   
2                    2.3                              4                 2   
3                    2.1                              3                 1   
4                    2.8                              3                 1   
5                    2.7                              5                 3   
6                    2.3                              3                 2   
7                    1.9                              3                 2   
8                    2.6                              4                 2   
9                    2.7                              3                 1   

     BMI  
0  30.20  
1  32.00  
2  24.71  
3  18.41  
4  14.39  
5  20.55  
6  23.76  
7  30.57  
8  32.34  
9  30.07

In [4]:
base_bpm = df[['Age','Avg_BPM']].to_numpy()

In [5]:
base_bpm

array([[ 56, 157],
       [ 46, 151],
       [ 32, 122],
       ...,
       [ 59, 120],
       [ 32, 146],
       [ 46, 146]], dtype=int64)

In [ ]:
grafico = px.scatter(base_bpm)
grafico

In [9]:
grafico1 = px.scatter(x=base_bpm[:,0], y=base_bpm[:,1])
grafico1

In [10]:
scatter_bpm = StandardScaler()
base_bpm = scatter_bpm.fit_transform(base_bpm)

In [11]:
base_bpm

array([[ 1.42234256,  0.92297044],
       [ 0.60096485,  0.50449409],
       [-0.54896396, -1.51814158],
       ...,
       [ 1.66875588, -1.65763369],
       [-0.54896396,  0.15576381],
       [ 0.60096485,  0.15576381]])

In [13]:
kmeans_bpm = KMeans(n_clusters=3)
kmeans_bpm.fit(base_bpm)

C:\Users\acsfarias\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=3)

In [15]:
kmeans_bpm


KMeans(n_clusters=3)

In [ ]:
centroides = kmeans_bpm.cluster_centers_
centroides

array([[ 0.06817333,  1.05833779],
       [-0.945649  , -0.67432862],
       [ 0.88872454, -0.63524131]])

In [21]:
scatter_bpm.inverse_transform(base_bpm)

array([[ 56., 157.],
       [ 46., 151.],
       [ 32., 122.],
       ...,
       [ 59., 120.],
       [ 32., 146.],
       [ 46., 146.]])

In [28]:
scatter_bpm.inverse_transform(centroides)

array([[ 39.51344086, 158.94086022],
       [ 27.1704918 , 134.09836066],
       [ 49.50337838, 134.65878378]])

In [23]:
rotulo = kmeans_bpm.labels_
rotulo

array([0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 1, 1,
       0, 0, 0, 0, 2, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 2, 1,
       0, 0, 0, 1, 2, 1, 0, 2, 2, 1, 1, 0, 0, 1, 0, 0, 2, 2, 1, 2, 1, 0,
       1, 1, 0, 0, 2, 1, 0, 1, 2, 2, 2, 2, 0, 1, 0, 2, 1, 1, 2, 0, 0, 0,
       0, 1, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 2,
       2, 2, 0, 1, 2, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0, 2, 0, 0, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 2, 0, 2, 1, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0,
       2, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 1, 0, 1, 1, 2, 1, 0, 1, 0, 2, 2, 0, 2, 1, 1, 1, 0, 2, 1, 0, 1,
       0, 1, 2, 0, 0, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 1, 0,
       1, 0, 1, 2, 2, 2, 2, 0, 2, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 1,
       1, 1, 1, 2, 2, 1, 2, 2, 0, 1, 1, 1, 2, 0, 2, 1, 1, 2, 0, 2, 0, 2,
       2, 0, 0, 0, 0, 1, 1, 2, 1, 2, 2, 2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2,
       0, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 2, 2, 2, 2,

In [ ]:
grafico1 = px.scatter(x=base_bpm[:,0], y=base_bpm[:,1], color=rotulo)
grafico2 = px.scatter(x=centroides[:,0], y=centroides[:,1], size=[15,15,15])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3